// Descripciones en español de los ítems del juego
// Extraídas de los bundles de localización de Unity (keys *_DESC y *_ABILITY)

export const DESCRIPTIONS = {
  'ARMOR_1': 'Carta de Armadura—Pesada. — Armadura de placas del ocaso',
  'ARMOR_10': 'Carta de Armadura—Mediana. — Cota de firmeza',
  'ARMOR_10_UPGRADED': 'Carta de Armadura—Mediana. — Cota de firmeza ',
  'ARMOR_11': 'Carta de Armadura—Mediana. — Jubón de asedio',
  'ARMOR_11_UPGRADED': 'Carta de Armadura—Mediana. — Jubón de asedio ',
  'ARMOR_12': 'Carta de Armadura—Ligera. — Atuendo noble',
  'ARMOR_12_UPGRADED': 'Carta de Armadura—Ligera. — Atuendo noble ',
  'ARMOR_13': 'Carta de Armadura—Ligera. — Túnica siniestra',
  'ARMOR_13_UPGRADED': 'Carta de Armadura—Ligera. — Túnica siniestra ',
  'ARMOR_14': 'Carta de Armadura—Ligera. — Chaleco de siete botones',
  'ARMOR_14_UPGRADED': 'Carta de Armadura—Ligera. — Chaleco de siete botones ',
  'ARMOR_15': 'Carta de Armadura—Ligera. — Capa imperceptible',
  'ARMOR_15_UPGRADED': 'Carta de Armadura—Ligera. — Capa imperceptible ',
  'ARMOR_16': 'Carta de Armadura—Ligera. — Túnica de camaradería',
  'ARMOR_16_UPGRADED': 'Carta de Armadura—Ligera. — Túnica de camaradería ',
  'ARMOR_17': 'Carta de Armadura—Ligera. — Túnica de Tarianor',
  'ARMOR_17_UPGRADED': 'Carta de Armadura—Ligera. — Túnica de Tarianor ',
  'ARMOR_18': 'Carta de Armadura—Ligera. — Capa del pesar',
  'ARMOR_18_UPGRADED': 'Carta de Armadura—Ligera. — Capa del pesar ',
  'ARMOR_19': 'Carta de Armadura—Pesada. — Armadura de placas monumental',
  'ARMOR_19_UPGRADED': 'Carta de Armadura—Pesada. — Armadura de placas monumental ',
  'ARMOR_1_UPGRADED': 'Carta de Armadura—Pesada. — Armadura de placas del ocaso ',
  'ARMOR_2': 'Carta de Armadura—Pesada. — Armadura de placas de la Piedra Sangrienta',
  'ARMOR_20': 'Carta de Armadura—Pesada. — Chapitel',
  'ARMOR_20_UPGRADED': 'Carta de Armadura—Pesada. — Chapitel ',
  'ARMOR_21': 'Carta de Armadura—Pesada. — Coraza del guardián de la luz',
  'ARMOR_21_UPGRADED': 'Carta de Armadura—Pesada. — Coraza del guardián de la luz ',
  'ARMOR_22': 'Carta de Armadura—Ligera. — Capucha de elfo del abismo',
  'ARMOR_22_UPGRADED': 'Carta de Armadura—Ligera. — Capucha de elfo del abismo ',
  'ARMOR_23': 'Carta de Armadura—Ligera. — Túnica de erudito',
  'ARMOR_23_UPGRADED': 'Carta de Armadura—Ligera. — Túnica de erudito ',
  'ARMOR_24': 'Carta de Armadura—Ligera. — Capucha reluciente',
  'ARMOR_24_UPGRADED': 'Carta de Armadura—Ligera. — Capucha reluciente ',
  'ARMOR_25': 'Carta de Armadura—Mediana. — Encrucijada',
  'ARMOR_25_UPGRADED': 'Carta de Armadura—Mediana. — Encrucijada ',
  'ARMOR_26': 'Carta de Armadura—Mediana. — Malla del cavador',
  'ARMOR_26_UPGRADED': 'Carta de Armadura—Mediana. — Malla del cavador ',
  'ARMOR_27': 'Carta de Armadura—Mediana. — Traje de cuero de explorador',
  'ARMOR_27_UPGRADED': 'Carta de Armadura—Mediana. — Traje de cuero de explorador ',
  'ARMOR_2_UPGRADED': 'Carta de Armadura—Pesada. — Armadura de placas de la Piedra Sangrienta ',
  'ARMOR_3': 'Carta de Armadura—Pesada. — Guardianes celestiales',
  'ARMOR_3_UPGRADED': 'Carta de Armadura—Pesada. — Guardianes celestiales ',
  'ARMOR_4': 'Carta de Armadura—Pesada. — Memorium',
  'ARMOR_4_UPGRADED': 'Carta de Armadura—Pesada. — Memorium ',
  'ARMOR_5': 'Carta de Armadura—Pesada. — Armadura de placas del caminante del alba',
  'ARMOR_5_UPGRADED': 'Carta de Armadura—Pesada. — Armadura de placas del caminante del alba ',
  'ARMOR_6': 'Carta de Armadura—Mediana. — Armadura de cuero del viajante',
  'ARMOR_6_UPGRADED': 'Carta de Armadura—Mediana. — Armadura de cuero del viajante ',
  'ARMOR_7': 'Carta de Armadura—Mediana. — Cota del anillo tormentoso',
  'ARMOR_7_UPGRADED': 'Carta de Armadura—Mediana. — Cota del anillo tormentoso ',
  'ARMOR_8': 'Carta de Armadura—Mediana. — Abrigo del enterrador',
  'ARMOR_8_UPGRADED': 'Carta de Armadura—Mediana. — Abrigo del enterrador ',
  'ARMOR_9': 'Carta de Armadura—Mediana. — Armadura de cuero del asesino',
  'ARMOR_9_UPGRADED': 'Carta de Armadura—Mediana. — Armadura de cuero del asesino ',
  'CSM_ANTIDOTE_POTION': 'Carta de Consumible—Común.',
  'CSM_ANTIDOTE_POTION_UPGRADED': 'Carta de Consumible—Común.',
  'CSM_CAUTION': 'Carta de Consumible—Especial.',
  'CSM_CAUTION_UPGRADED': 'Carta de Consumible—Especial.',
  'CSM_CRIMSON_POTION': 'Carta de Consumible—Limitado.',
  'CSM_CRIMSON_POTION_UPGRADED': 'Carta de Consumible—Limitado.',
  'CSM_EFFICACIOUS': 'Carta de Consumible—Limitado.',
  'CSM_EFFICACIOUS_UPGRADED': 'Carta de Consumible—Limitado.',
  'CSM_ENDURANCE_POTION': 'Carta de Consumible—Especial.',
  'CSM_ENDURANCE_POTION_UPGRADED': 'Carta de Consumible—Especial.',
  'CSM_FIRE_GRENADE': 'Carta de Consumible—Común.',
  'CSM_FIRE_GRENADE_UPGRADED': 'Carta de Consumible—Común.',
  'CSM_FOCUS_POTION': 'Carta de Consumible—Común.',
  'CSM_FOCUS_POTION_UPGRADED': 'Carta de Consumible—Común.',
  'CSM_GLITTERDUST': 'Carta de Consumible—Común.',
  'CSM_GLITTERDUST_UPGRADED': 'Carta de Consumible—Común.',
  'CSM_GUARDIAN_POTION': 'Carta de Consumible—Limitado.',
  'CSM_GUARDIAN_POTION_UPGRADED': 'Carta de Consumible—Limitado.',
  'CSM_INVISIBILITY_POTION': 'Carta de Consumible—Especial.',
  'CSM_INVISIBILITY_POTION_UPGRADED': 'Carta de Consumible—Especial.',
  'CSM_KNACK': 'Carta de Consumible—Especial.',
  'CSM_KNACK_UPGRADED': 'Carta de Consumible—Especial.',
  'CSM_MAGE_DUST': 'Carta de Consumible—Limitado.',
  'CSM_MAGE_DUST_UPGRADED': 'Carta de Consumible—Limitado.',
  'CSM_MIASMA_GRENADE': 'Carta de Consumible—Común.',
  'CSM_MIASMA_GRENADE_UPGRADED': 'Carta de Consumible—Común.',
  'CSM_MUD_POTION': 'Carta de Consumible—Especial.',
  'CSM_MUD_POTION_UPGRADED': 'Carta de Consumible—Especial.',
  'CSM_MUTATION_POTION': 'Carta de Consumible—Especial.',
  'CSM_MUTATION_POTION_UPGRADED': 'Carta de Consumible—Especial.',
  'CSM_PHOENIX_ASH_POTION': 'Carta de Consumible—Especial.',
  'CSM_PHOENIX_ASH_POTION_UPGRADED': 'Carta de Consumible—Especial.',
  'CSM_RABBITFOOT_POTION': 'Carta de Consumible—Común.',
  'CSM_RABBITFOOT_POTION_UPGRADED': 'Carta de Consumible—Común.',
  'CSM_ROGUE_SWEAT': 'Carta de Consumible—Limitado.',
  'CSM_ROGUE_SWEAT_UPGRADED': 'Carta de Consumible—Limitado.',
  'CSM_SLAYER_POTION': 'Carta de Consumible—Especial.',
  'CSM_SLAYER_POTION_UPGRADED': 'Carta de Consumible—Especial.',
  'CSM_SMOKE_BOMB': 'Carta de Consumible—Limitado.',
  'CSM_SMOKE_BOMB_UPGRADED': 'Carta de Consumible—Limitado.',
  'CSM_STALWART': 'Carta de Consumible—Limitado.',
  'CSM_STALWART_UPGRADED': 'Carta de Consumible—Limitado.',
  'CSM_VIGOR_POTION': 'Carta de Consumible—Común.',
  'CSM_VIGOR_POTION_UPGRADED': 'Carta de Consumible—Común.',
  'CSM_WARRIOR_BREATH': 'Carta de Consumible—Limitado.',
  'CSM_WARRIOR_BREATH_UPGRADED': 'Carta de Consumible—Limitado.',
  'CSM_WHIRLWIND': 'Carta de Consumible—Limitado.',
  'CSM_WHIRLWIND_UPGRADED': 'Carta de Consumible—Limitado.',
  'MAT_ANEMOS': 'La esencia mágica del viento: rápida, caótica y libre.',
  'MAT_AQUOS': 'La esencia mágica del agua: fluida, abrumadora y en constante cambio.',
  'MAT_BONE': 'Los huesos de diversas criaturas, desde pequeñas aves hasta especies dracónicas.',
  'MAT_CLOTH': 'Textiles de todo Terrinoth.',
  'MAT_CURIOS': 'Todo tipo de cosas que dejaron aventureros, viajeros, soldados y buscadores.',
  'MAT_FORTUNOS': 'La esencia mágica de la suerte: alentadora, desafiante e impredecible.',
  'MAT_HERBS': 'Diversas plantas con propiedades medicinales o culinarias.',
  'MAT_IGNOS': 'La esencia mágica del fuego: crepitante, abrasadora e incontenible.',
  'MAT_LEATHER': 'Pieles de animal tratadas que se usan comúnmente en armaduras y equipo.',
  'MAT_LUMOS': 'La esencia mágica de la luz: brillante, auténtica y clara.',
  'MAT_METAL': 'Fragmentos refinados por innumerables artesanos para armas y herramientas.',
  'MAT_MINERALS': 'Piedra en bruto extraída y comerciada en todos los rincones de Terrinoth.',
  'MAT_MORTOS': 'La esencia mágica de la muerte: profunda, dolorosa y escalofriante.',
  'MAT_TERROS': 'La esencia mágica de la tierra: fuerte, robusta y atemporal.',
  'MAT_TOXOS': 'La esencia mágica de la putrefacción: natural, terrible y enfermiza.',
  'MAT_UMBROS': 'La esencia mágica de la sombra: oscura, informe e incognoscible.',
  'MAT_VIGOS': 'La esencia mágica de la vida: fresca, revitalizadora y sustentadora.',
  'TRINKET10_ID': 'Después de que derrotes a un enemigo, si es la primera vez en la campaña que un héroe que tenga este accesorio equipado derrota a ese tipo de enemigo, obtén una receta especial.',
  'TRINKET11_ID': 'Cuando se produce el paso del tiempo, cada héroe puede elegir el beneficio alternativo mostrado en vez de descartar <style=Term><link=TERM_FATIGUE></link></style>.',
  'TRINKET12_ID': 'Durante tu ataque, si el enemigo tiene más vida que cada uno de los demás enemigos, el <style=Term><link=TERM_DAMAGE></link></style> de tu arma aumenta en 1.',
  'TRINKET13_ID': 'Después de que derrotes a un enemigo durante un ataque, 1 enemigo aleatorio distinto sufre una cantidad de <style=Term><link=TERM_DAMAGE></link></style> igual al 10% de la vida inicial del enemigo derrotado.',
  'TRINKET15_ID': 'Durante tu ataque, si el enemigo no ha sido atacado en esta ronda, obtiene 1 estado aleatorio.',
  'TRINKET16_ID': 'Después de tu ataque, a veces obtienes un beneficio adicional.',
  'TRINKET17_ID': 'El daño de ataque de cada enemigo <style=Term><link=TERM_ENFEEBLED>debilitado</link></style> se reduce un 10% adicional.',
  'TRINKET18_ID': 'Después de que interactúes por primera vez en cada ronda, a veces obtienes una acción adicional.',
  'TRINKET19_ID': 'Cuando aparece un enemigo, queda <style=Term><link=TERM_EXPOSED>expuesto</link></style>.',
  'TRINKET1_ID': 'Durante tu ataque, si el enemigo ya está dañado, sufre 3 <style=Term><link=TERM_DAMAGE></link></style> adicionales.',
  'TRINKET20_ID': 'Tus ataques obtienen un tipo de daño aleatorio. Después de tu ataque, revela una <style=Term><link=TERM_WEAKNESSES>debilidad</link></style> enemiga aleatoria.',
  'TRINKET21_ID': 'Alguien está buscando esto.',
  'TRINKET2_ID': 'Al comienzo de cada misión, obtén 1 consumible aleatorio.',
  'TRINKET3_ID': 'Después de que un enemigo sea derrotado, si los héroes no obtienen materiales de creación, obtienen una pequeña cantidad de oro.',
  'TRINKET4_ID': 'Después de que un héroe quede <style=Term><link=TERM_WOUNDS>herido</link></style>, otro héroe recibe un beneficio aleatorio.',
  'TRINKET5_ID': 'Cuando quedas <style=Term><link=TERM_WOUNDS>herido</link></style>, obtienes una <style=Term><link=TERM_INJURIES>dolencia</link></style> especial.',
  'TRINKET6_ID': 'Después de que realices una <style=Term><link=TERM_TESTS>prueba</link></style> e introduzcas los resultados en la aplicación, se añaden 0–2 <style=Term><link=TERM_SUCCESS></link></style> adicionales.',
  'TRINKET7_ID': 'Durante tu primer ataque en cada ronda, la probabilidad de tu capacidad secundaria aumenta un 5%.',
  'TRINKET8_ID': 'Durante tus primeros 3 ataques de cada misión, el enemigo sufre 7 <style=Term><link=TERM_DAMAGE></link></style> adicionales y queda <style=Term><link=TERM_DAZED>conmocionado</link></style>.',
  'TRINKET9_ID': 'Durante tu ataque, si el enemigo no ha sido atacado en esta ronda, sufre 1–7 <style=Term><link=TERM_DAMAGE></link></style> adicionales.',
};
