// Materiales de crafteo de Descent: Legends of the Dark
// Precios extraídos de los assets del juego (Value = sell price, buyPrice = Value*2)
// sellPrice = precio cuando vendemos al mercader
// buyPrice = precio cuando compramos al mercader

export const MATERIALS = [
  {
    id: 'MAT_BONE',
    name: 'Hueso',
    nameEn: 'Bone',
    image: '/assets/materials/bone.png',
    sellPrice: 5,
    buyPrice: 10,
  },
  {
    id: 'MAT_CLOTH',
    name: 'Tela',
    nameEn: 'Cloth',
    image: '/assets/materials/cloth.png',
    sellPrice: 5,
    buyPrice: 10,
  },
  {
    id: 'MAT_CURIOS',
    name: 'Ingredientes',
    nameEn: 'Curios',
    image: '/assets/materials/curios.png',
    sellPrice: 5,
    buyPrice: 10,
  },
  {
    id: 'MAT_HERBS',
    name: 'Hierbas',
    nameEn: 'Herbs',
    image: '/assets/materials/herbs.png',
    sellPrice: 5,
    buyPrice: 10,
  },
  {
    id: 'MAT_LEATHER',
    name: 'Cuero',
    nameEn: 'Leather',
    image: '/assets/materials/leather.png',
    sellPrice: 5,
    buyPrice: 10,
  },
  {
    id: 'MAT_METAL',
    name: 'Metal',
    nameEn: 'Metal',
    image: '/assets/materials/metal.png',
    sellPrice: 5,
    buyPrice: 10,
  },
  {
    id: 'MAT_MINERALS',
    name: 'Minerales',
    nameEn: 'Minerals',
    image: '/assets/materials/minerals.png',
    sellPrice: 5,
    buyPrice: 10,
  },
  {
    id: 'MAT_ANEMOS',
    name: 'Anemos',
    nameEn: 'Anemos',
    image: '/assets/materials/anemos.png',
    sellPrice: 25,
    buyPrice: 50,
  },
  {
    id: 'MAT_AQUOS',
    name: 'Aquos',
    nameEn: 'Aquos',
    image: '/assets/materials/aquos.png',
    sellPrice: 25,
    buyPrice: 50,
  },
  {
    id: 'MAT_IGNOS',
    name: 'Ignos',
    nameEn: 'Ignos',
    image: '/assets/materials/ignos.png',
    sellPrice: 25,
    buyPrice: 50,
  },
  {
    id: 'MAT_TERROS',
    name: 'Terros',
    nameEn: 'Terros',
    image: '/assets/materials/terros.png',
    sellPrice: 25,
    buyPrice: 50,
  },
  {
    id: 'MAT_FORTUNOS',
    name: 'Fortunos',
    nameEn: 'Fortunos',
    image: '/assets/materials/fortunos.png',
    sellPrice: 30,
    buyPrice: 60,
  },
  {
    id: 'MAT_LUMOS',
    name: 'Lumos',
    nameEn: 'Lumos',
    image: '/assets/materials/lumos.png',
    sellPrice: 30,
    buyPrice: 60,
  },
  {
    id: 'MAT_MORTOS',
    name: 'Mortos',
    nameEn: 'Mortos',
    image: '/assets/materials/mortos.png',
    sellPrice: 30,
    buyPrice: 60,
  },
  {
    id: 'MAT_TOXOS',
    name: 'Toxos',
    nameEn: 'Toxos',
    image: '/assets/materials/toxos.png',
    sellPrice: 30,
    buyPrice: 60,
  },
  {
    id: 'MAT_UMBROS',
    name: 'Umbros',
    nameEn: 'Umbros',
    image: '/assets/materials/umbros.png',
    sellPrice: 30,
    buyPrice: 60,
  },
  {
    id: 'MAT_VIGOS',
    name: 'Vigos',
    nameEn: 'Vigos',
    image: '/assets/materials/vigos.png',
    sellPrice: 30,
    buyPrice: 60,
  },
];

export const MATERIALS_BY_ID = Object.fromEntries(MATERIALS.map(m => [m.id, m]));
