// Materiales de crafteo del juego Descent: Legends of the Dark
// Datos extraídos de los bundles de Unity del juego
// buyPrice / sellPrice: null = precio no encontrado en los assets; se pueden editar desde Ajustes

export const MATERIALS = [
  {
    id: 'MAT_ANEMOS',
    name: 'Anemos',
    nameEn: 'Anemos',
    description: 'La esencia mágica del viento: rápida, caótica y libre.',
    image: '/assets/materials/anemos.png',
    buyPrice: null,   // TODO: verificar en app
    sellPrice: null,  // TODO: verificar en app
  },
  {
    id: 'MAT_AQUOS',
    name: 'Aquos',
    nameEn: 'Aquos',
    description: 'La esencia mágica del agua: fluida, abrumadora y en constante cambio.',
    image: '/assets/materials/aquos.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_BONE',
    name: 'Hueso',
    nameEn: 'Bone',
    description: 'Los huesos de diversas criaturas, desde pequeñas aves hasta especies dracónicas.',
    image: '/assets/materials/bone.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_CLOTH',
    name: 'Tela',
    nameEn: 'Cloth',
    description: 'Textiles de todo Terrinoth.',
    image: '/assets/materials/cloth.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_CURIOS',
    name: 'Ingredientes',
    nameEn: 'Curios',
    description: 'Todo tipo de cosas que dejaron aventureros, viajeros, soldados y buscadores.',
    image: '/assets/materials/curios.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_FORTUNOS',
    name: 'Fortunos',
    nameEn: 'Fortunos',
    description: 'La esencia mágica de la suerte: alentadora, desafiante e impredecible.',
    image: '/assets/materials/fortunos.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_HERBS',
    name: 'Hierbas',
    nameEn: 'Herbs',
    description: 'Diversas plantas con propiedades medicinales o culinarias.',
    image: '/assets/materials/herbs.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_IGNOS',
    name: 'Ignos',
    nameEn: 'Ignos',
    description: 'La esencia mágica del fuego: crepitante, abrasadora e incontenible.',
    image: '/assets/materials/ignos.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_LEATHER',
    name: 'Cuero',
    nameEn: 'Leather',
    description: 'Pieles de animal tratadas que se usan comúnmente como material para equipo.',
    image: '/assets/materials/leather.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_LUMOS',
    name: 'Lumos',
    nameEn: 'Lumos',
    description: 'La esencia mágica de la luz: brillante, auténtica y clara.',
    image: '/assets/materials/lumos.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_METAL',
    name: 'Metal',
    nameEn: 'Metal',
    description: 'Fragmentos refinados por innumerables artesanos para armas y herramientas.',
    image: '/assets/materials/metal.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_MINERALS',
    name: 'Minerales',
    nameEn: 'Minerals',
    description: 'Piedra en bruto extraída y comerciada en todo Terrinoth.',
    image: '/assets/materials/minerals.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_MORTOS',
    name: 'Mortos',
    nameEn: 'Mortos',
    description: 'La esencia mágica de la muerte: profunda, dolorosa y fría.',
    image: '/assets/materials/mortos.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_TERROS',
    name: 'Terros',
    nameEn: 'Terros',
    description: 'La esencia mágica de la tierra: fuerte, robusta y natural.',
    image: '/assets/materials/terros.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_TOXOS',
    name: 'Toxos',
    nameEn: 'Toxos',
    description: 'La esencia mágica de la putrefacción: natural, terrible e inmortaliza.',
    image: '/assets/materials/toxos.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_UMBROS',
    name: 'Umbros',
    nameEn: 'Umbros',
    description: 'La esencia mágica de la sombra: oscura, informe e indescifrable.',
    image: '/assets/materials/umbros.png',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'MAT_VIGOS',
    name: 'Vigos',
    nameEn: 'Vigos',
    description: 'La esencia mágica de la vida: fresca, revitalizadora y pura.',
    image: '/assets/materials/vigos.png',
    buyPrice: null,
    sellPrice: null,
  },
];

// Mapa indexado por ID para acceso rápido
export const MATERIALS_BY_ID = Object.fromEntries(MATERIALS.map(m => [m.id, m]));
