// Recetas de crafteo del juego Descent: Legends of the Dark
// Datos extraídos de los bundles de Unity del juego
// Ingredientes y costes en oro: null = no disponible en los assets del juego
// Estos datos deben verificarse con el juego físico

// Recetas de partes de arma (craftear la parte)
// Slot B y C tienen recetas; el slot A se compra en tienda (no se craftea)
export const WEAPON_PART_RECIPES = [
  // === ARCO (BOW) ===
  { id: 'RECIPE_WEAPON_PART_B_BOW_1', itemId: 'WEAPON_PART_B_BOW_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_BOW_2', itemId: 'WEAPON_PART_B_BOW_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_BOW_3', itemId: 'WEAPON_PART_B_BOW_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_BOW_4', itemId: 'WEAPON_PART_B_BOW_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_BOW_5', itemId: 'WEAPON_PART_B_BOW_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_BOW_1', itemId: 'WEAPON_PART_C_BOW_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_BOW_2', itemId: 'WEAPON_PART_C_BOW_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_BOW_3', itemId: 'WEAPON_PART_C_BOW_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_BOW_4', itemId: 'WEAPON_PART_C_BOW_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_BOW_5', itemId: 'WEAPON_PART_C_BOW_5', goldCost: null, ingredients: null },
  // === BALLESTA (CROSSBOW) ===
  { id: 'RECIPE_WEAPON_PART_B_CROSSBOW_1', itemId: 'WEAPON_PART_B_CROSSBOW_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_CROSSBOW_2', itemId: 'WEAPON_PART_B_CROSSBOW_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_CROSSBOW_3', itemId: 'WEAPON_PART_B_CROSSBOW_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_CROSSBOW_4', itemId: 'WEAPON_PART_B_CROSSBOW_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_CROSSBOW_5', itemId: 'WEAPON_PART_B_CROSSBOW_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_CROSSBOW_1', itemId: 'WEAPON_PART_C_CROSSBOW_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_CROSSBOW_2', itemId: 'WEAPON_PART_C_CROSSBOW_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_CROSSBOW_3', itemId: 'WEAPON_PART_C_CROSSBOW_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_CROSSBOW_4', itemId: 'WEAPON_PART_C_CROSSBOW_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_CROSSBOW_5', itemId: 'WEAPON_PART_C_CROSSBOW_5', goldCost: null, ingredients: null },
  // === HOJAS GEMELAS (DUAL_BLADES) ===
  { id: 'RECIPE_WEAPON_PART_B_DUAL_BLADES_1', itemId: 'WEAPON_PART_B_DUAL_BLADES_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_DUAL_BLADES_2', itemId: 'WEAPON_PART_B_DUAL_BLADES_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_DUAL_BLADES_3', itemId: 'WEAPON_PART_B_DUAL_BLADES_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_DUAL_BLADES_4', itemId: 'WEAPON_PART_B_DUAL_BLADES_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_DUAL_BLADES_5', itemId: 'WEAPON_PART_B_DUAL_BLADES_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_DUAL_BLADES_1', itemId: 'WEAPON_PART_C_DUAL_BLADES_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_DUAL_BLADES_2', itemId: 'WEAPON_PART_C_DUAL_BLADES_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_DUAL_BLADES_3', itemId: 'WEAPON_PART_C_DUAL_BLADES_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_DUAL_BLADES_4', itemId: 'WEAPON_PART_C_DUAL_BLADES_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_DUAL_BLADES_5', itemId: 'WEAPON_PART_C_DUAL_BLADES_5', goldCost: null, ingredients: null },
  // === GUANTELETE (GAUNTLET) ===
  { id: 'RECIPE_WEAPON_PART_B_GAUNTLET_1', itemId: 'WEAPON_PART_B_GAUNTLET_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_GAUNTLET_2', itemId: 'WEAPON_PART_B_GAUNTLET_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_GAUNTLET_3', itemId: 'WEAPON_PART_B_GAUNTLET_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_GAUNTLET_4', itemId: 'WEAPON_PART_B_GAUNTLET_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_GAUNTLET_5', itemId: 'WEAPON_PART_B_GAUNTLET_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_GAUNTLET_1', itemId: 'WEAPON_PART_C_GAUNTLET_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_GAUNTLET_2', itemId: 'WEAPON_PART_C_GAUNTLET_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_GAUNTLET_3', itemId: 'WEAPON_PART_C_GAUNTLET_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_GAUNTLET_4', itemId: 'WEAPON_PART_C_GAUNTLET_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_GAUNTLET_5', itemId: 'WEAPON_PART_C_GAUNTLET_5', goldCost: null, ingredients: null },
  // === MARTILLO (HAMMER) ===
  { id: 'RECIPE_WEAPON_PART_B_HAMMER_1', itemId: 'WEAPON_PART_B_HAMMER_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_HAMMER_2', itemId: 'WEAPON_PART_B_HAMMER_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_HAMMER_3', itemId: 'WEAPON_PART_B_HAMMER_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_HAMMER_4', itemId: 'WEAPON_PART_B_HAMMER_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_HAMMER_5', itemId: 'WEAPON_PART_B_HAMMER_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_HAMMER_1', itemId: 'WEAPON_PART_C_HAMMER_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_HAMMER_2', itemId: 'WEAPON_PART_C_HAMMER_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_HAMMER_3', itemId: 'WEAPON_PART_C_HAMMER_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_HAMMER_4', itemId: 'WEAPON_PART_C_HAMMER_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_HAMMER_5', itemId: 'WEAPON_PART_C_HAMMER_5', goldCost: null, ingredients: null },
  // === CUCHILLOS (KNIVES) ===
  { id: 'RECIPE_WEAPON_PART_B_KNIVES_1', itemId: 'WEAPON_PART_B_KNIVES_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_KNIVES_2', itemId: 'WEAPON_PART_B_KNIVES_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_KNIVES_3', itemId: 'WEAPON_PART_B_KNIVES_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_KNIVES_4', itemId: 'WEAPON_PART_B_KNIVES_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_KNIVES_5', itemId: 'WEAPON_PART_B_KNIVES_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_KNIVES_1', itemId: 'WEAPON_PART_C_KNIVES_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_KNIVES_2', itemId: 'WEAPON_PART_C_KNIVES_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_KNIVES_3', itemId: 'WEAPON_PART_C_KNIVES_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_KNIVES_4', itemId: 'WEAPON_PART_C_KNIVES_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_KNIVES_5', itemId: 'WEAPON_PART_C_KNIVES_5', goldCost: null, ingredients: null },
  // === LANZA (SPEAR) ===
  { id: 'RECIPE_WEAPON_PART_B_SPEAR_1', itemId: 'WEAPON_PART_B_SPEAR_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_SPEAR_2', itemId: 'WEAPON_PART_B_SPEAR_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_SPEAR_3', itemId: 'WEAPON_PART_B_SPEAR_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_SPEAR_4', itemId: 'WEAPON_PART_B_SPEAR_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_SPEAR_5', itemId: 'WEAPON_PART_B_SPEAR_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SPEAR_1', itemId: 'WEAPON_PART_C_SPEAR_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SPEAR_2', itemId: 'WEAPON_PART_C_SPEAR_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SPEAR_3', itemId: 'WEAPON_PART_C_SPEAR_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SPEAR_4', itemId: 'WEAPON_PART_C_SPEAR_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SPEAR_5', itemId: 'WEAPON_PART_C_SPEAR_5', goldCost: null, ingredients: null },
  // === BÁCULO (STAFF) ===
  { id: 'RECIPE_WEAPON_PART_B_STAFF_1', itemId: 'WEAPON_PART_B_STAFF_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_STAFF_2', itemId: 'WEAPON_PART_B_STAFF_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_STAFF_3', itemId: 'WEAPON_PART_B_STAFF_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_STAFF_4', itemId: 'WEAPON_PART_B_STAFF_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_STAFF_5', itemId: 'WEAPON_PART_B_STAFF_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_STAFF_1', itemId: 'WEAPON_PART_C_STAFF_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_STAFF_2', itemId: 'WEAPON_PART_C_STAFF_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_STAFF_3', itemId: 'WEAPON_PART_C_STAFF_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_STAFF_4', itemId: 'WEAPON_PART_C_STAFF_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_STAFF_5', itemId: 'WEAPON_PART_C_STAFF_5', goldCost: null, ingredients: null },
  // === ESPADA (SWORD) ===
  { id: 'RECIPE_WEAPON_PART_B_SWORD_1', itemId: 'WEAPON_PART_B_SWORD_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_SWORD_2', itemId: 'WEAPON_PART_B_SWORD_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_SWORD_3', itemId: 'WEAPON_PART_B_SWORD_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_SWORD_4', itemId: 'WEAPON_PART_B_SWORD_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_SWORD_5', itemId: 'WEAPON_PART_B_SWORD_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SWORD_1', itemId: 'WEAPON_PART_C_SWORD_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SWORD_2', itemId: 'WEAPON_PART_C_SWORD_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SWORD_3', itemId: 'WEAPON_PART_C_SWORD_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SWORD_4', itemId: 'WEAPON_PART_C_SWORD_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_SWORD_5', itemId: 'WEAPON_PART_C_SWORD_5', goldCost: null, ingredients: null },
  // === VARITA (WAND) ===
  { id: 'RECIPE_WEAPON_PART_B_WAND_1', itemId: 'WEAPON_PART_B_WAND_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WAND_2', itemId: 'WEAPON_PART_B_WAND_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WAND_3', itemId: 'WEAPON_PART_B_WAND_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WAND_4', itemId: 'WEAPON_PART_B_WAND_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WAND_5', itemId: 'WEAPON_PART_B_WAND_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WAND_1', itemId: 'WEAPON_PART_C_WAND_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WAND_2', itemId: 'WEAPON_PART_C_WAND_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WAND_3', itemId: 'WEAPON_PART_C_WAND_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WAND_4', itemId: 'WEAPON_PART_C_WAND_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WAND_5', itemId: 'WEAPON_PART_C_WAND_5', goldCost: null, ingredients: null },
  // === CAMPANA DE GUERRA (WARBELL) ===
  { id: 'RECIPE_WEAPON_PART_B_WARBELL_1', itemId: 'WEAPON_PART_B_WARBELL_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WARBELL_2', itemId: 'WEAPON_PART_B_WARBELL_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WARBELL_3', itemId: 'WEAPON_PART_B_WARBELL_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WARBELL_4', itemId: 'WEAPON_PART_B_WARBELL_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WARBELL_5', itemId: 'WEAPON_PART_B_WARBELL_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARBELL_1', itemId: 'WEAPON_PART_C_WARBELL_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARBELL_2', itemId: 'WEAPON_PART_C_WARBELL_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARBELL_3', itemId: 'WEAPON_PART_C_WARBELL_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARBELL_4', itemId: 'WEAPON_PART_C_WARBELL_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARBELL_5', itemId: 'WEAPON_PART_C_WARBELL_5', goldCost: null, ingredients: null },
  // === MARTILLO DE GUERRA (WARHAMMER) ===
  { id: 'RECIPE_WEAPON_PART_B_WARHAMMER_1', itemId: 'WEAPON_PART_B_WARHAMMER_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WARHAMMER_2', itemId: 'WEAPON_PART_B_WARHAMMER_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WARHAMMER_3', itemId: 'WEAPON_PART_B_WARHAMMER_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WARHAMMER_4', itemId: 'WEAPON_PART_B_WARHAMMER_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_B_WARHAMMER_5', itemId: 'WEAPON_PART_B_WARHAMMER_5', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARHAMMER_1', itemId: 'WEAPON_PART_C_WARHAMMER_1', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARHAMMER_2', itemId: 'WEAPON_PART_C_WARHAMMER_2', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARHAMMER_3', itemId: 'WEAPON_PART_C_WARHAMMER_3', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARHAMMER_4', itemId: 'WEAPON_PART_C_WARHAMMER_4', goldCost: null, ingredients: null },
  { id: 'RECIPE_WEAPON_PART_C_WARHAMMER_5', itemId: 'WEAPON_PART_C_WARHAMMER_5', goldCost: null, ingredients: null },
];

// Recetas de consumibles
export const CONSUMABLE_RECIPES = [
  { id: 'RECIPE_CSM_ANTIDOTE_POTION', itemId: 'CSM_ANTIDOTE_POTION', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_CRIMSON_POTION', itemId: 'CSM_CRIMSON_POTION', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_EFFICACIOUS', itemId: 'CSM_EFFICACIOUS', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_FIRE_GRENADE', itemId: 'CSM_FIRE_GRENADE', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_FOCUS_POTION', itemId: 'CSM_FOCUS_POTION', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_GLITTERDUST', itemId: 'CSM_GLITTERDUST', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_GUARDIAN_POTION', itemId: 'CSM_GUARDIAN_POTION', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_MAGE_DUST', itemId: 'CSM_MAGE_DUST', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_MIASMA_GRENADE', itemId: 'CSM_MIASMA_GRENADE', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_RABBITFOOT_POTION', itemId: 'CSM_RABBITFOOT_POTION', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_ROGUE_SWEAT', itemId: 'CSM_ROGUE_SWEAT', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_SMOKE_BOMB', itemId: 'CSM_SMOKE_BOMB', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_STALWART', itemId: 'CSM_STALWART', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_VIGOR_POTION', itemId: 'CSM_VIGOR_POTION', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_WARRIOR_BREATH', itemId: 'CSM_WARRIOR_BREATH', goldCost: null, ingredients: null },
  { id: 'RECIPE_CSM_WHIRLWIND', itemId: 'CSM_WHIRLWIND', goldCost: null, ingredients: null },
];

export const ALL_RECIPES = [...WEAPON_PART_RECIPES, ...CONSUMABLE_RECIPES];
export const RECIPES_BY_ID = Object.fromEntries(ALL_RECIPES.map(r => [r.id, r]));
