// Partes de armas del juego Descent: Legends of the Dark
// Datos extraídos de los bundles de Unity del juego
// buyPrice / sellPrice: null = precio no encontrado; editable desde Ajustes
// Slot A = Hoja/Cabeza, Slot B = Empuñadura/Mango, Slot C = Accesorio/Punta

export const WEAPON_PARTS = [
  {
    "id": "WEAPON_PART_A_BOW_0",
    "slot": "A",
    "weaponType": "BOW",
    "level": 0,
    "name": "Arco largo básico",
    "nameEn": "Basic Longbow",
    "weaponId": "WEAPON_BOW",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_BOW_1",
    "slot": "A",
    "weaponType": "BOW",
    "level": 1,
    "name": "Arco de madera sangrienta",
    "nameEn": "Bloodwood Bow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow a1 - bloodwood.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_BOW_2",
    "slot": "A",
    "weaponType": "BOW",
    "level": 2,
    "name": "Arco de raíz negra",
    "nameEn": "Blackroot Bow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow a2 - blackroot.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_BOW_3",
    "slot": "A",
    "weaponType": "BOW",
    "level": 3,
    "name": "Arco de avellano de bruja",
    "nameEn": "Witch Hazel Bow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow a3 - witchhazel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_BOW_4",
    "slot": "A",
    "weaponType": "BOW",
    "level": 4,
    "name": "Arco aullante",
    "nameEn": "Howling Bow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow a4 - howling.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_BOW_5",
    "slot": "A",
    "weaponType": "BOW",
    "level": 5,
    "name": "Arco centinela",
    "nameEn": "Sentinel Bow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow a5 - sentinel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_BOW_0",
    "slot": "B",
    "weaponType": "BOW",
    "level": 0,
    "name": "Cuerda",
    "nameEn": "String",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow b0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_BOW_1",
    "slot": "B",
    "weaponType": "BOW",
    "level": 1,
    "name": "Cuerda de encaje nocturno",
    "nameEn": "Nightlace String",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow b1 - nightlace string.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_BOW_2",
    "slot": "B",
    "weaponType": "BOW",
    "level": 2,
    "name": "Cuerda de seda",
    "nameEn": "Silken String",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow b2 - silken string.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_BOW_3",
    "slot": "B",
    "weaponType": "BOW",
    "level": 3,
    "name": "Cuerda de origen salvaje",
    "nameEn": "Wildborn String",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow b3 - wildborn string.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_BOW_4",
    "slot": "B",
    "weaponType": "BOW",
    "level": 4,
    "name": "Cuerda de luna llena",
    "nameEn": "Full Moon String",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow b4 - full moon string.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_BOW_5",
    "slot": "B",
    "weaponType": "BOW",
    "level": 5,
    "name": "Cuerda vibrante",
    "nameEn": "Thrumming String",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow b5 - thrumming string.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_BOW_0",
    "slot": "C",
    "weaponType": "BOW",
    "level": 0,
    "name": "Flecha",
    "nameEn": "Arrow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow c0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_BOW_1",
    "slot": "C",
    "weaponType": "BOW",
    "level": 1,
    "name": "Flecha de tirador",
    "nameEn": "Marksman's Arrow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow c1 - marksman's arrow.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_BOW_2",
    "slot": "C",
    "weaponType": "BOW",
    "level": 2,
    "name": "Flecha de liana siniestra",
    "nameEn": "Direvine Arrow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow c2 - direvine arrow.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_BOW_3",
    "slot": "C",
    "weaponType": "BOW",
    "level": 3,
    "name": "Flecha crepuscular",
    "nameEn": "Twilight Arrow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow c3 - twilight arrow.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_BOW_4",
    "slot": "C",
    "weaponType": "BOW",
    "level": 4,
    "name": "Flecha de grito de halcón",
    "nameEn": "Hawk-Cry Arrow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow c4 - hawk-cry arrow.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_BOW_5",
    "slot": "C",
    "weaponType": "BOW",
    "level": 5,
    "name": "Flecha precisa",
    "nameEn": "Pinpoint Arrow",
    "weaponId": "WEAPON_BOW",
    "image": "/assets/weapon_parts/bow c5 - pinpoint arrow.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_CROSSBOW_0",
    "slot": "A",
    "weaponType": "CROSSBOW",
    "level": 0,
    "name": "Ballesta básica",
    "nameEn": "Basic Crossbow",
    "weaponId": "WEAPON_CROSSBOW",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_CROSSBOW_1",
    "slot": "A",
    "weaponType": "CROSSBOW",
    "level": 1,
    "name": "Ballesta de puntería certera",
    "nameEn": "True Aim Crossbow",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow a1 - dualpower.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_CROSSBOW_2",
    "slot": "A",
    "weaponType": "CROSSBOW",
    "level": 2,
    "name": "Ballesta de potencia doble",
    "nameEn": "Dualpower Crossbow",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow a2 - crisscross.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_CROSSBOW_3",
    "slot": "A",
    "weaponType": "CROSSBOW",
    "level": 3,
    "name": "Ballesta de tejido élfico",
    "nameEn": "Elfweave Crossbow",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow a3 - woven.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_CROSSBOW_4",
    "slot": "A",
    "weaponType": "CROSSBOW",
    "level": 4,
    "name": "Ballesta de retroceso",
    "nameEn": "Kickback Crossbow",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow a4 - kickback.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_CROSSBOW_5",
    "slot": "A",
    "weaponType": "CROSSBOW",
    "level": 5,
    "name": "Ballesta de tiro lejano",
    "nameEn": "Longsight Crossbow",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow a5 - longsight.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_CROSSBOW_0",
    "slot": "B",
    "weaponType": "CROSSBOW",
    "level": 0,
    "name": "Culata",
    "nameEn": "Stock",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow b0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_CROSSBOW_1",
    "slot": "B",
    "weaponType": "CROSSBOW",
    "level": 1,
    "name": "Culata de madera gnómica",
    "nameEn": "Gnomewood Stock",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow b1 - gnomewood stock.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_CROSSBOW_2",
    "slot": "B",
    "weaponType": "CROSSBOW",
    "level": 2,
    "name": "Culata descomunal",
    "nameEn": "Mammoth Stock",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow b2 - mammoth stock.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_CROSSBOW_3",
    "slot": "B",
    "weaponType": "CROSSBOW",
    "level": 3,
    "name": "Culata de madera norteña",
    "nameEn": "Northwood Stock",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow b3 - northwood stock.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_CROSSBOW_4",
    "slot": "B",
    "weaponType": "CROSSBOW",
    "level": 4,
    "name": "Culata fortalecedora",
    "nameEn": "Bracing Stock",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow b4 - bracing stock.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_CROSSBOW_5",
    "slot": "B",
    "weaponType": "CROSSBOW",
    "level": 5,
    "name": "Culata de recarga",
    "nameEn": "Reloading Stock",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow b5 - reloading stock.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_CROSSBOW_0",
    "slot": "C",
    "weaponType": "CROSSBOW",
    "level": 0,
    "name": "Virotes",
    "nameEn": "Bolts",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow c0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_CROSSBOW_1",
    "slot": "C",
    "weaponType": "CROSSBOW",
    "level": 1,
    "name": "Virotes dentados",
    "nameEn": "Barbed Bolts",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow c1 - barbed bolts.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_CROSSBOW_2",
    "slot": "C",
    "weaponType": "CROSSBOW",
    "level": 2,
    "name": "Virotes de espiral",
    "nameEn": "Spiral Bolts",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow c2 - spiral bolts.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_CROSSBOW_3",
    "slot": "C",
    "weaponType": "CROSSBOW",
    "level": 3,
    "name": "Virotes aullantes",
    "nameEn": "Screamer Bolts",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow c3 - screamer bolts.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_CROSSBOW_4",
    "slot": "C",
    "weaponType": "CROSSBOW",
    "level": 4,
    "name": "Virotes marcadores",
    "nameEn": "Marking Bolts",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow c4 - guiding bolts.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_CROSSBOW_5",
    "slot": "C",
    "weaponType": "CROSSBOW",
    "level": 5,
    "name": "Virotes de astillamiento",
    "nameEn": "Splintering Bolts",
    "weaponId": "WEAPON_CROSSBOW",
    "image": "/assets/weapon_parts/crossbow c5 - splintering bolts.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_DUAL_BLADES_0",
    "slot": "A",
    "weaponType": "DUAL_BLADES",
    "level": 0,
    "name": "Hojas de duelo básicas",
    "nameEn": "Basic Duel Blades",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_DUAL_BLADES_1",
    "slot": "A",
    "weaponType": "DUAL_BLADES",
    "level": 1,
    "name": "Hojas gemelas",
    "nameEn": "Mirror Blades",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades a1 - mirror.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_DUAL_BLADES_2",
    "slot": "A",
    "weaponType": "DUAL_BLADES",
    "level": 2,
    "name": "Hojas del vidente",
    "nameEn": "Seer's Blades",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades a2 - seer.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_DUAL_BLADES_3",
    "slot": "A",
    "weaponType": "DUAL_BLADES",
    "level": 3,
    "name": "Hojas susurrantes",
    "nameEn": "Whispering Blades",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades a3 - whispering.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_DUAL_BLADES_4",
    "slot": "A",
    "weaponType": "DUAL_BLADES",
    "level": 4,
    "name": "Hojas danzantes",
    "nameEn": "Dancing Blades",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades a4 - dancing.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_DUAL_BLADES_5",
    "slot": "A",
    "weaponType": "DUAL_BLADES",
    "level": 5,
    "name": "Hojas hambrientas",
    "nameEn": "Hungry Blades",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades a5 - hungry.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_DUAL_BLADES_0",
    "slot": "B",
    "weaponType": "DUAL_BLADES",
    "level": 0,
    "name": "Arma secundaria",
    "nameEn": "Offhand",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades b0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_DUAL_BLADES_1",
    "slot": "B",
    "weaponType": "DUAL_BLADES",
    "level": 1,
    "name": "Arma secundaria de cristal",
    "nameEn": "Glass Offhand",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades b1 - glass offhand.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_DUAL_BLADES_2",
    "slot": "B",
    "weaponType": "DUAL_BLADES",
    "level": 2,
    "name": "Arma secundaria con gancho",
    "nameEn": "Hooked Offhand",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades b2 - hooked offhand.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_DUAL_BLADES_3",
    "slot": "B",
    "weaponType": "DUAL_BLADES",
    "level": 3,
    "name": "Arma secundaria olvidada",
    "nameEn": "Forgotten Offhand",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades b3 - forgotten offhand.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_DUAL_BLADES_4",
    "slot": "B",
    "weaponType": "DUAL_BLADES",
    "level": 4,
    "name": "Arma secundaria de metal estelar",
    "nameEn": "Star Metal Offhand",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades b4 - star metal offhand.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_DUAL_BLADES_5",
    "slot": "B",
    "weaponType": "DUAL_BLADES",
    "level": 5,
    "name": "Arma secundaria de leonx",
    "nameEn": "Leonx Offhand",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades b5 - leonx offhand.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_DUAL_BLADES_0",
    "slot": "C",
    "weaponType": "DUAL_BLADES",
    "level": 0,
    "name": "Puños",
    "nameEn": "Pommels",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades c0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_DUAL_BLADES_1",
    "slot": "C",
    "weaponType": "DUAL_BLADES",
    "level": 1,
    "name": "Puño de piedra roja",
    "nameEn": "Redstone Pommel",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades c1 - redstone pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_DUAL_BLADES_2",
    "slot": "C",
    "weaponType": "DUAL_BLADES",
    "level": 2,
    "name": "Puño de escritura sanguínea",
    "nameEn": "Bloodscript Pommel",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades c2 - bloodscript pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_DUAL_BLADES_3",
    "slot": "C",
    "weaponType": "DUAL_BLADES",
    "level": 3,
    "name": "Puño trenzado",
    "nameEn": "Braided Pommel",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades c3 - braided pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_DUAL_BLADES_4",
    "slot": "C",
    "weaponType": "DUAL_BLADES",
    "level": 4,
    "name": "Puño dorado",
    "nameEn": "Gilded Pommel",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades c4 - gilded pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_DUAL_BLADES_5",
    "slot": "C",
    "weaponType": "DUAL_BLADES",
    "level": 5,
    "name": "Puño de guardia de garra",
    "nameEn": "Clawguard Pommel",
    "weaponId": "WEAPON_DUAL_BLADES",
    "image": "/assets/weapon_parts/dual blades c5 - clawguard pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_GAUNTLET_0",
    "slot": "A",
    "weaponType": "GAUNTLET",
    "level": 0,
    "name": "Guantelete básico",
    "nameEn": "Basic Gauntlet",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_GAUNTLET_1",
    "slot": "A",
    "weaponType": "GAUNTLET",
    "level": 1,
    "name": "Guantelete de garra sombría",
    "nameEn": "Shadowclaw Gauntlet",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet a1 - shadowstone.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_GAUNTLET_2",
    "slot": "A",
    "weaponType": "GAUNTLET",
    "level": 2,
    "name": "Guantelete acolmillado",
    "nameEn": "Fanged Gauntlet",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet a2 - fanged.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_GAUNTLET_3",
    "slot": "A",
    "weaponType": "GAUNTLET",
    "level": 3,
    "name": "Guantelete disruptor",
    "nameEn": "Disrupter Gauntlet",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet a3 - disrupter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_GAUNTLET_4",
    "slot": "A",
    "weaponType": "GAUNTLET",
    "level": 4,
    "name": "Guantelete implacable",
    "nameEn": "Relentless Gauntlet",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet a4 - relentless.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_GAUNTLET_5",
    "slot": "A",
    "weaponType": "GAUNTLET",
    "level": 5,
    "name": "Guantelete de libación vital",
    "nameEn": "Life-Drinking Gauntlet",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet a5 - life drinking.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_GAUNTLET_0",
    "slot": "B",
    "weaponType": "GAUNTLET",
    "level": 0,
    "name": "Guante",
    "nameEn": "Glove",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet b0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_GAUNTLET_1",
    "slot": "B",
    "weaponType": "GAUNTLET",
    "level": 1,
    "name": "Guantes de tejido sombrío",
    "nameEn": "Shadow-Weave Gloves",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet b1 - shadow-weave gloves.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_GAUNTLET_2",
    "slot": "B",
    "weaponType": "GAUNTLET",
    "level": 2,
    "name": "Guantes de garra",
    "nameEn": "Clawed Gloves",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet b2 - clawed gloves.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_GAUNTLET_3",
    "slot": "B",
    "weaponType": "GAUNTLET",
    "level": 3,
    "name": "Guantes sanguinarios",
    "nameEn": "Bloodthirsty Gloves",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet b3 - bloodthirsty gloves.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_GAUNTLET_4",
    "slot": "B",
    "weaponType": "GAUNTLET",
    "level": 4,
    "name": "Guantes de susurro",
    "nameEn": "Whisper Gloves",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet b4 - whisper gloves.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_GAUNTLET_5",
    "slot": "B",
    "weaponType": "GAUNTLET",
    "level": 5,
    "name": "Guantes de ala de draco",
    "nameEn": "Drakewing Gloves",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet b5 - drakewing gloves.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_GAUNTLET_0",
    "slot": "C",
    "weaponType": "GAUNTLET",
    "level": 0,
    "name": "Brazalete",
    "nameEn": "Bracer",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet c0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_GAUNTLET_1",
    "slot": "C",
    "weaponType": "GAUNTLET",
    "level": 1,
    "name": "Brazaletes de piedrasombría",
    "nameEn": "Shadowstone Bracers",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet c1 - shadowstone bracers.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_GAUNTLET_2",
    "slot": "C",
    "weaponType": "GAUNTLET",
    "level": 2,
    "name": "Brazaletes pesados",
    "nameEn": "Heavy Bracers",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet c2 - heavy bracers.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_GAUNTLET_3",
    "slot": "C",
    "weaponType": "GAUNTLET",
    "level": 3,
    "name": "Brazaletes crueles",
    "nameEn": "Cruel Bracers",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet c3 - cruel bracers.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_GAUNTLET_4",
    "slot": "C",
    "weaponType": "GAUNTLET",
    "level": 4,
    "name": "Brazaletes mordedores",
    "nameEn": "Biting Bracers",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet c4 - biting bracers.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_GAUNTLET_5",
    "slot": "C",
    "weaponType": "GAUNTLET",
    "level": 5,
    "name": "Brazaletes aferradores",
    "nameEn": "Grasping Bracers",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/gauntlet c5 - grasping bracers.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_HAMMER_0",
    "slot": "A",
    "weaponType": "HAMMER",
    "level": 0,
    "name": "Martillo básico",
    "nameEn": "Basic Hammer",
    "weaponId": "WEAPON_HAMMER",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_HAMMER_1",
    "slot": "A",
    "weaponType": "HAMMER",
    "level": 1,
    "name": "Martillo de dos cabezas",
    "nameEn": "Double-Headed Hammer",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer a1 - double headed.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_HAMMER_2",
    "slot": "A",
    "weaponType": "HAMMER",
    "level": 2,
    "name": "Martillo con gancho",
    "nameEn": "Hooked Hammer",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer a2 - hooked.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_HAMMER_3",
    "slot": "A",
    "weaponType": "HAMMER",
    "level": 3,
    "name": "Martillo con púas",
    "nameEn": "Spiked Hammer",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer a3 - spiked.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_HAMMER_4",
    "slot": "A",
    "weaponType": "HAMMER",
    "level": 4,
    "name": "Martillo de pensar",
    "nameEn": "Thinking Hammer",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer a4 - thinking.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_HAMMER_5",
    "slot": "A",
    "weaponType": "HAMMER",
    "level": 5,
    "name": "Martillo de rebote",
    "nameEn": "Rebound Hammer",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer a5 - rebound.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_HAMMER_0",
    "slot": "B",
    "weaponType": "HAMMER",
    "level": 0,
    "name": "Mango",
    "nameEn": "Haft",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer b0 - starter haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_HAMMER_1",
    "slot": "B",
    "weaponType": "HAMMER",
    "level": 1,
    "name": "Mango de Dunwarr",
    "nameEn": "Dunwarrik Haft",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer b1 - dunwarik haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_HAMMER_2",
    "slot": "B",
    "weaponType": "HAMMER",
    "level": 2,
    "name": "Mango de Forja",
    "nameEn": "Forgik Haft",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer b2 - forgik haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_HAMMER_3",
    "slot": "B",
    "weaponType": "HAMMER",
    "level": 3,
    "name": "Mango kehlik",
    "nameEn": "Kehlik Haft",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer b3 - kehlik haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_HAMMER_4",
    "slot": "B",
    "weaponType": "HAMMER",
    "level": 4,
    "name": "Mango del inventor",
    "nameEn": "Inventor's Haft",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer b4 - inventor's haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_HAMMER_5",
    "slot": "B",
    "weaponType": "HAMMER",
    "level": 5,
    "name": "Mango del reaprovechador",
    "nameEn": "Salvager Haft",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer b5 - salvager haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_HAMMER_0",
    "slot": "C",
    "weaponType": "HAMMER",
    "level": 0,
    "name": "Agarre",
    "nameEn": "Grip",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer c0 - starter grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_HAMMER_1",
    "slot": "C",
    "weaponType": "HAMMER",
    "level": 1,
    "name": "Agarre del herrero",
    "nameEn": "Smith's Grip",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer c1 - workman's grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_HAMMER_2",
    "slot": "C",
    "weaponType": "HAMMER",
    "level": 2,
    "name": "Agarre de guardia",
    "nameEn": "Guardsman's Grip",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer c2 - guardsman's grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_HAMMER_3",
    "slot": "C",
    "weaponType": "HAMMER",
    "level": 3,
    "name": "Agarre del devastador",
    "nameEn": "Devastator's Grip",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer c3 - devastation's grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_HAMMER_4",
    "slot": "C",
    "weaponType": "HAMMER",
    "level": 4,
    "name": "Agarre del manipulador",
    "nameEn": "Tinker's Grip",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer c4 - tinker's grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_HAMMER_5",
    "slot": "C",
    "weaponType": "HAMMER",
    "level": 5,
    "name": "Agarre de la urraca",
    "nameEn": "Magpie's Grip",
    "weaponId": "WEAPON_HAMMER",
    "image": "/assets/weapon_parts/hammer c5 - magpie's grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_KNIVES_0",
    "slot": "A",
    "weaponType": "KNIVES",
    "level": 0,
    "name": "Cuchillos arrojadizos básicos",
    "nameEn": "Basic Throwing Knives",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_KNIVES_1",
    "slot": "A",
    "weaponType": "KNIVES",
    "level": 1,
    "name": "Cuchillos de punta espinada",
    "nameEn": "Thorntip Knives",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives a1 - thorntip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_KNIVES_2",
    "slot": "A",
    "weaponType": "KNIVES",
    "level": 2,
    "name": "Cuchillos dentados",
    "nameEn": "Barbed Knives",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives a2 - barbed.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_KNIVES_3",
    "slot": "A",
    "weaponType": "KNIVES",
    "level": 3,
    "name": "Cuchillos de corte fragmentado",
    "nameEn": "Shattercut Knives",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives a3 - shattercut.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_KNIVES_4",
    "slot": "A",
    "weaponType": "KNIVES",
    "level": 4,
    "name": "Cuchillos cristalinos",
    "nameEn": "Crystal Knives",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives a4 - crystal.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_KNIVES_5",
    "slot": "A",
    "weaponType": "KNIVES",
    "level": 5,
    "name": "Cuchillos de fragmento silbante",
    "nameEn": "Whistleshard Knives",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives a5 - whistleshard.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_KNIVES_0",
    "slot": "B",
    "weaponType": "KNIVES",
    "level": 0,
    "name": "Agarre",
    "nameEn": "Grip",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives b0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_KNIVES_1",
    "slot": "B",
    "weaponType": "KNIVES",
    "level": 1,
    "name": "Agarre equilibrado",
    "nameEn": "Balanced Grip",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives b1 - balanced grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_KNIVES_2",
    "slot": "B",
    "weaponType": "KNIVES",
    "level": 2,
    "name": "Agarre de pinchos",
    "nameEn": "Spiked Grip",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives b2 - spiked grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_KNIVES_3",
    "slot": "B",
    "weaponType": "KNIVES",
    "level": 3,
    "name": "Agarre torcido",
    "nameEn": "Hooked Grip",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives b3 - hooked grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_KNIVES_4",
    "slot": "B",
    "weaponType": "KNIVES",
    "level": 4,
    "name": "Agarre de madera viva",
    "nameEn": "Livewood Grip",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives b4 - livewood grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_KNIVES_5",
    "slot": "B",
    "weaponType": "KNIVES",
    "level": 5,
    "name": "Agarra colmilludo",
    "nameEn": "Fanged Grip",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives b5 - fanged grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_KNIVES_0",
    "slot": "C",
    "weaponType": "KNIVES",
    "level": 0,
    "name": "Cinturón",
    "nameEn": "Belt",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives c0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_KNIVES_1",
    "slot": "C",
    "weaponType": "KNIVES",
    "level": 1,
    "name": "Cinturón de caminante nocturno",
    "nameEn": "Nightwalker Belt",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives c1 - nightwalker belt.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_KNIVES_2",
    "slot": "C",
    "weaponType": "KNIVES",
    "level": 2,
    "name": "Cinturón de ataque de cobra",
    "nameEn": "Cobrastrike Belt",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives c2 - cobrastrike bracers.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_KNIVES_3",
    "slot": "C",
    "weaponType": "KNIVES",
    "level": 3,
    "name": "Fajín de tres deseos",
    "nameEn": "Threewishes Sash",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives c3 - threewishes sash.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_KNIVES_4",
    "slot": "C",
    "weaponType": "KNIVES",
    "level": 4,
    "name": "Cinturón de brote silvestre",
    "nameEn": "Wildbloom Belt",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives c4 - wildbloom belt.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_KNIVES_5",
    "slot": "C",
    "weaponType": "KNIVES",
    "level": 5,
    "name": "Cinturón de golpe crepuscular",
    "nameEn": "Duskstrike Belt",
    "weaponId": "WEAPON_THROWING_KNIVES",
    "image": "/assets/weapon_parts/knives c5 - duskstrike belt.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SPEAR_0",
    "slot": "A",
    "weaponType": "SPEAR",
    "level": 0,
    "name": "Lanza",
    "nameEn": "Spear",
    "weaponId": "WEAPON_SPEAR",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SPEAR_1",
    "slot": "A",
    "weaponType": "SPEAR",
    "level": 1,
    "name": "Lanza de Torrentera",
    "nameEn": "Riverwatch Spear",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear a1 - lotus.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SPEAR_2",
    "slot": "A",
    "weaponType": "SPEAR",
    "level": 2,
    "name": "Lanza lunar",
    "nameEn": "Lunar Spear",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear a2 - lunar.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SPEAR_3",
    "slot": "A",
    "weaponType": "SPEAR",
    "level": 3,
    "name": "Lanza de forjado solar",
    "nameEn": "Sunforged Spear",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear a3 - sunforged.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SPEAR_4",
    "slot": "A",
    "weaponType": "SPEAR",
    "level": 4,
    "name": "Lanza con banderines",
    "nameEn": "Pennant Spear",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear a4 - pennant.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SPEAR_5",
    "slot": "A",
    "weaponType": "SPEAR",
    "level": 5,
    "name": "Lanza de campeón",
    "nameEn": "Champion's Spear",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear a5 - champion's.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SPEAR_0",
    "slot": "B",
    "weaponType": "SPEAR",
    "level": 0,
    "name": "Mango",
    "nameEn": "Haft",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear b0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SPEAR_1",
    "slot": "B",
    "weaponType": "SPEAR",
    "level": 1,
    "name": "Asta retorcida",
    "nameEn": "Twisting Haft",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear b1 - twisting haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SPEAR_2",
    "slot": "B",
    "weaponType": "SPEAR",
    "level": 2,
    "name": "Asta grabada",
    "nameEn": "Engraved Haft",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear b2 - engraved haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SPEAR_3",
    "slot": "B",
    "weaponType": "SPEAR",
    "level": 3,
    "name": "Asta superior",
    "nameEn": "Superior Haft",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear b3 - superior haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SPEAR_4",
    "slot": "B",
    "weaponType": "SPEAR",
    "level": 4,
    "name": "Mango agitado",
    "nameEn": "Roiling Haft",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear b4 - roiling haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SPEAR_5",
    "slot": "B",
    "weaponType": "SPEAR",
    "level": 5,
    "name": "Mango inflexible",
    "nameEn": "Unyielding Haft",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear b5 - unyielding haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SPEAR_0",
    "slot": "C",
    "weaponType": "SPEAR",
    "level": 0,
    "name": "Cola",
    "nameEn": "Tail",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear c0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SPEAR_1",
    "slot": "C",
    "weaponType": "SPEAR",
    "level": 1,
    "name": "Cola radiante",
    "nameEn": "Radiant Tail",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear c1 - radiant tail.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SPEAR_2",
    "slot": "C",
    "weaponType": "SPEAR",
    "level": 2,
    "name": "Cola del anochecer",
    "nameEn": "Nightfall Tail",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear c2 - nightfall tail.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SPEAR_3",
    "slot": "C",
    "weaponType": "SPEAR",
    "level": 3,
    "name": "Cola de la serpiente",
    "nameEn": "Serpent's Tail",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear c3 - serpent's tail.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SPEAR_4",
    "slot": "C",
    "weaponType": "SPEAR",
    "level": 4,
    "name": "Cola mordiente",
    "nameEn": "Biting Tail",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear c4 - biting tail.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SPEAR_5",
    "slot": "C",
    "weaponType": "SPEAR",
    "level": 5,
    "name": "Cola anclada",
    "nameEn": "Anchored Tail",
    "weaponId": "WEAPON_SPEAR",
    "image": "/assets/weapon_parts/spear c5 - anchored tail.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_STAFF_0",
    "slot": "A",
    "weaponType": "STAFF",
    "level": 0,
    "name": "Bastón básico",
    "nameEn": "Basic Staff",
    "weaponId": "WEAPON_STAFF",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_STAFF_1",
    "slot": "A",
    "weaponType": "STAFF",
    "level": 1,
    "name": "Bastón retorcido",
    "nameEn": "Crook'd Staff",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff a1 - crookd.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_STAFF_2",
    "slot": "A",
    "weaponType": "STAFF",
    "level": 2,
    "name": "Bastón cristalino",
    "nameEn": "Crystalline Staff",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff a2 - crystal.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_STAFF_3",
    "slot": "A",
    "weaponType": "STAFF",
    "level": 3,
    "name": "Bastón perenne",
    "nameEn": "Evergreen Staff",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff a3 - evergreen.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_STAFF_4",
    "slot": "A",
    "weaponType": "STAFF",
    "level": 4,
    "name": "Bastón ceniciento",
    "nameEn": "Ashen Staff",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff a4 - ashen.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_STAFF_5",
    "slot": "A",
    "weaponType": "STAFF",
    "level": 5,
    "name": "Bastón de guardián",
    "nameEn": "Guardian Staff",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff a5 - guardian.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_STAFF_0",
    "slot": "B",
    "weaponType": "STAFF",
    "level": 0,
    "name": "Envoltura",
    "nameEn": "Wrap",
    "weaponId": "WEAPON_STAFF",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_STAFF_1",
    "slot": "B",
    "weaponType": "STAFF",
    "level": 1,
    "name": "Envoltura de Puerto Cano",
    "nameEn": "Greyhaven Wrap",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff b1 - greyhaven wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_STAFF_2",
    "slot": "B",
    "weaponType": "STAFF",
    "level": 2,
    "name": "Envoltura escarlata",
    "nameEn": "Scarlet Wrap",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff b2 - scarlet wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_STAFF_3",
    "slot": "B",
    "weaponType": "STAFF",
    "level": 3,
    "name": "Envoltura del jinete",
    "nameEn": "Rider's Wrap",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff b3 - rider's wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_STAFF_4",
    "slot": "B",
    "weaponType": "STAFF",
    "level": 4,
    "name": "Envoltura de escama llameante",
    "nameEn": "Flamescale Wrap",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff b4 - flamescale wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_STAFF_5",
    "slot": "B",
    "weaponType": "STAFF",
    "level": 5,
    "name": "Envoltura vendada",
    "nameEn": "Banded Wrap",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff b5 - banded wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_STAFF_0",
    "slot": "C",
    "weaponType": "STAFF",
    "level": 0,
    "name": "Infusión",
    "nameEn": "Lacing",
    "weaponId": "WEAPON_STAFF",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_STAFF_1",
    "slot": "C",
    "weaponType": "STAFF",
    "level": 1,
    "name": "Infusión sanguina",
    "nameEn": "Blood Vein Lacing",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff c1 - blood vein lacing.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_STAFF_2",
    "slot": "C",
    "weaponType": "STAFF",
    "level": 2,
    "name": "Infusión de tormenta",
    "nameEn": "Stormwind Lacing",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff c2 - stormfront lacing.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_STAFF_3",
    "slot": "C",
    "weaponType": "STAFF",
    "level": 3,
    "name": "Infusión de abundancia",
    "nameEn": "Goldbloom Lacing",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff c3 - goldbloom lacing.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_STAFF_4",
    "slot": "C",
    "weaponType": "STAFF",
    "level": 4,
    "name": "Infusión ambarina",
    "nameEn": "Ember Lacing",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff c4 - ember lacing.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_STAFF_5",
    "slot": "C",
    "weaponType": "STAFF",
    "level": 5,
    "name": "Infusión protegida",
    "nameEn": "Warded Lacing",
    "weaponId": "WEAPON_STAFF",
    "image": "/assets/weapon_parts/staff c5 - warded lacing.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SWORD_0",
    "slot": "A",
    "weaponType": "SWORD",
    "level": 0,
    "name": "Espada básica",
    "nameEn": "Basic Sword",
    "weaponId": "WEAPON_SWORD",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SWORD_1",
    "slot": "A",
    "weaponType": "SWORD",
    "level": 1,
    "name": "Hoja de guardián",
    "nameEn": "Warden's Blade",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword a1 - gladius blade.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SWORD_2",
    "slot": "A",
    "weaponType": "SWORD",
    "level": 2,
    "name": "Hoja alada",
    "nameEn": "Wing Blade",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword a2 - wing blade.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SWORD_3",
    "slot": "A",
    "weaponType": "SWORD",
    "level": 3,
    "name": "Hoja de diamante",
    "nameEn": "Diamond Blade",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword a3 - diamond blade.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SWORD_4",
    "slot": "A",
    "weaponType": "SWORD",
    "level": 4,
    "name": "Hoja de embestida",
    "nameEn": "Lunging Blade",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword a4 - lunging blade.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_SWORD_5",
    "slot": "A",
    "weaponType": "SWORD",
    "level": 5,
    "name": "Hoja de la Ciudadela",
    "nameEn": "Citadel Blade",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword a5 - citadel blade.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SWORD_0",
    "slot": "B",
    "weaponType": "SWORD",
    "level": 0,
    "name": "Guardia",
    "nameEn": "Guard",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword b0 - starter guard.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SWORD_1",
    "slot": "B",
    "weaponType": "SWORD",
    "level": 1,
    "name": "Guardia de jinete norteño",
    "nameEn": "Northrider Guard",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword b1 - reverberating guard.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SWORD_2",
    "slot": "B",
    "weaponType": "SWORD",
    "level": 2,
    "name": "Guardia de jinete occidental",
    "nameEn": "Westrider Guard",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword b2 - winged guard.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SWORD_3",
    "slot": "B",
    "weaponType": "SWORD",
    "level": 3,
    "name": "Guardia de jinete oriental",
    "nameEn": "Eastrider Guard",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword b3 - clawed guard.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SWORD_4",
    "slot": "B",
    "weaponType": "SWORD",
    "level": 4,
    "name": "Guardia rompedora",
    "nameEn": "Breaker Guard",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword b4 - breaker guard.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_SWORD_5",
    "slot": "B",
    "weaponType": "SWORD",
    "level": 5,
    "name": "Guardia de parapeto",
    "nameEn": "Parapet Guard",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword b5 - parapet guard.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SWORD_0",
    "slot": "C",
    "weaponType": "SWORD",
    "level": 0,
    "name": "Empuñadura",
    "nameEn": "Hilt",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword c0 - starter hilt.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SWORD_1",
    "slot": "C",
    "weaponType": "SWORD",
    "level": 1,
    "name": "Empuñadura resolutiva",
    "nameEn": "Resolute Hilt",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword c1 - resolute hilt.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SWORD_2",
    "slot": "C",
    "weaponType": "SWORD",
    "level": 2,
    "name": "Empuñadura triunfante",
    "nameEn": "Triumphant Hilt",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword c2 - triumphant hilt.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SWORD_3",
    "slot": "C",
    "weaponType": "SWORD",
    "level": 3,
    "name": "Empuñadura de conmemoración",
    "nameEn": "Remembrance Hilt",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword c3 - remembrance hilt.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SWORD_4",
    "slot": "C",
    "weaponType": "SWORD",
    "level": 4,
    "name": "Empuñadura del comandante",
    "nameEn": "Commander's Hilt",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword c4 - commander's hilt.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_SWORD_5",
    "slot": "C",
    "weaponType": "SWORD",
    "level": 5,
    "name": "Empuñadura del guardián",
    "nameEn": "Guardian Hilt",
    "weaponId": "WEAPON_SWORD",
    "image": "/assets/weapon_parts/sword c5 - guardian hilt.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WAND_0",
    "slot": "A",
    "weaponType": "WAND",
    "level": 0,
    "name": "Varita básica",
    "nameEn": "Basic Wand",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WAND_1",
    "slot": "A",
    "weaponType": "WAND",
    "level": 1,
    "name": "Varita destellante",
    "nameEn": "Glimmering Wand",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand a1 - glimmering.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WAND_2",
    "slot": "A",
    "weaponType": "WAND",
    "level": 2,
    "name": "Varita de raíz de roble",
    "nameEn": "Oakroot Wand",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand a2 - oakroot.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WAND_3",
    "slot": "A",
    "weaponType": "WAND",
    "level": 3,
    "name": "Varita tocada por las estrellas",
    "nameEn": "Star-Touched Wand",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand a3 - star touched.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WAND_4",
    "slot": "A",
    "weaponType": "WAND",
    "level": 4,
    "name": "Varita deformante",
    "nameEn": "Warping Wand",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand a4 - warping.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WAND_5",
    "slot": "A",
    "weaponType": "WAND",
    "level": 5,
    "name": "Varita de arco",
    "nameEn": "Arcing Wand",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand a5 - arcing.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WAND_0",
    "slot": "B",
    "weaponType": "WAND",
    "level": 0,
    "name": "Envoltura",
    "nameEn": "Wrap",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WAND_1",
    "slot": "B",
    "weaponType": "WAND",
    "level": 1,
    "name": "Envoltura de veta plateada",
    "nameEn": "Silver Vein Wrap",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand b1 - silver vein wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WAND_2",
    "slot": "B",
    "weaponType": "WAND",
    "level": 2,
    "name": "Envoltura de la naturaleza",
    "nameEn": "Nature Wrap",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand b2 - nature wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WAND_3",
    "slot": "B",
    "weaponType": "WAND",
    "level": 3,
    "name": "Envoltura del magíster",
    "nameEn": "Magister's Wrap",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand b3 - magister's wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WAND_4",
    "slot": "B",
    "weaponType": "WAND",
    "level": 4,
    "name": "Envoltura de cielo nocturno",
    "nameEn": "Nightsky Wrap",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand b4 - nightsky wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WAND_5",
    "slot": "B",
    "weaponType": "WAND",
    "level": 5,
    "name": "Envoltura del erudito",
    "nameEn": "Scholar's Wrap",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand b5 - scholar's wrap.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WAND_0",
    "slot": "C",
    "weaponType": "WAND",
    "level": 0,
    "name": "Adorno",
    "nameEn": "Ornament",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WAND_1",
    "slot": "C",
    "weaponType": "WAND",
    "level": 1,
    "name": "Adorno de pluma",
    "nameEn": "Feather Ornament",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand c1 - feather ornament.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WAND_2",
    "slot": "C",
    "weaponType": "WAND",
    "level": 2,
    "name": "Adorno de garra",
    "nameEn": "Claw Ornament",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand c2 - claw ornament.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WAND_3",
    "slot": "C",
    "weaponType": "WAND",
    "level": 3,
    "name": "Adorno de ojo",
    "nameEn": "Eye Ornament",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand c3 - eye ornament.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WAND_4",
    "slot": "C",
    "weaponType": "WAND",
    "level": 4,
    "name": "Adorno de ala de polilla",
    "nameEn": "Mothwing Ornament",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand c4 - mothwing ornament.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WAND_5",
    "slot": "C",
    "weaponType": "WAND",
    "level": 5,
    "name": "Adorno volcánico",
    "nameEn": "Volcanic Ornament",
    "weaponId": "WEAPON_WAND_OF_WINDS",
    "image": "/assets/weapon_parts/wand c5 - volcanic ornament.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARBELL_0",
    "slot": "A",
    "weaponType": "WARBELL",
    "level": 0,
    "name": "Campana de guerra básica",
    "nameEn": "Basic Warbell",
    "weaponId": "WEAPON_WARBELL",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARBELL_1",
    "slot": "A",
    "weaponType": "WARBELL",
    "level": 1,
    "name": "Campana de guerra espinada",
    "nameEn": "Ironthorn Warbell",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell a1 - ironthorn.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARBELL_2",
    "slot": "A",
    "weaponType": "WARBELL",
    "level": 2,
    "name": "Campana de guerra dorada",
    "nameEn": "Gilded Warbell",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell a2 - gilded.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARBELL_3",
    "slot": "A",
    "weaponType": "WARBELL",
    "level": 3,
    "name": "Campana de guerra aullante",
    "nameEn": "Shrieking Warbell",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell a3 - shrieking.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARBELL_4",
    "slot": "A",
    "weaponType": "WARBELL",
    "level": 4,
    "name": "Campana de guerra de clarín",
    "nameEn": "Clarion Warbell",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell a4 - clarion.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARBELL_5",
    "slot": "A",
    "weaponType": "WARBELL",
    "level": 5,
    "name": "Campana de guerra humilde",
    "nameEn": "Humble Warbell",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell a5 - humble.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARBELL_0",
    "slot": "B",
    "weaponType": "WARBELL",
    "level": 0,
    "name": "Agarre",
    "nameEn": "Grip",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell b0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARBELL_1",
    "slot": "B",
    "weaponType": "WARBELL",
    "level": 1,
    "name": "Agarre de espolón",
    "nameEn": "Talon Grip",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell b1 - talon grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARBELL_2",
    "slot": "B",
    "weaponType": "WARBELL",
    "level": 2,
    "name": "Agarre enjoyado",
    "nameEn": "Jeweled Grip",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell b2 - jeweled grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARBELL_3",
    "slot": "B",
    "weaponType": "WARBELL",
    "level": 3,
    "name": "Agarre de pinchos",
    "nameEn": "Spiked Grip",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell b3 - spiked grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARBELL_4",
    "slot": "B",
    "weaponType": "WARBELL",
    "level": 4,
    "name": "Agarre regio",
    "nameEn": "Royal Grip",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell b4 - royal grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARBELL_5",
    "slot": "B",
    "weaponType": "WARBELL",
    "level": 5,
    "name": "Agarre de alivio",
    "nameEn": "Respite Grip",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell b5 - respite grip.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARBELL_0",
    "slot": "C",
    "weaponType": "WARBELL",
    "level": 0,
    "name": "Mango",
    "nameEn": "Haft",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell c0 - starter.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARBELL_1",
    "slot": "C",
    "weaponType": "WARBELL",
    "level": 1,
    "name": "Mango reforzado",
    "nameEn": "Reinforced Haft",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell c1 - reinforced haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARBELL_2",
    "slot": "C",
    "weaponType": "WARBELL",
    "level": 2,
    "name": "Mango inscrito",
    "nameEn": "Inscribed Haft",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell c2 - inscribed haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARBELL_3",
    "slot": "C",
    "weaponType": "WARBELL",
    "level": 3,
    "name": "Mango resonante",
    "nameEn": "Ringing Haft",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell c3 - ringing haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARBELL_4",
    "slot": "C",
    "weaponType": "WARBELL",
    "level": 4,
    "name": "Mango majestuoso",
    "nameEn": "Majestic Haft",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell c4 - majestic haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARBELL_5",
    "slot": "C",
    "weaponType": "WARBELL",
    "level": 5,
    "name": "Mango bloqueador",
    "nameEn": "Locking Haft",
    "weaponId": "WEAPON_WARBELL",
    "image": "/assets/weapon_parts/warbell c5 - locking haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARHAMMER_0",
    "slot": "A",
    "weaponType": "WARHAMMER",
    "level": 0,
    "name": "Martillo de guerra básico",
    "nameEn": "Basic Warhammer",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": null,
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARHAMMER_1",
    "slot": "A",
    "weaponType": "WARHAMMER",
    "level": 1,
    "name": "Martillo de guerra lastrado",
    "nameEn": "Weighted Warhammer",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer a1 - weighted.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARHAMMER_2",
    "slot": "A",
    "weaponType": "WARHAMMER",
    "level": 2,
    "name": "Martillo de guerra vengador",
    "nameEn": "Avenging Warhammer",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer a2 - avenging.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARHAMMER_3",
    "slot": "A",
    "weaponType": "WARHAMMER",
    "level": 3,
    "name": "Martillo de guerra de Mariscal",
    "nameEn": "Marshal's Warhammer",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer a3 - marshal's.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARHAMMER_4",
    "slot": "A",
    "weaponType": "WARHAMMER",
    "level": 4,
    "name": "Martillo de guerra demoledor",
    "nameEn": "Sundering Warhammer",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer a4 - sundering.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_A_WARHAMMER_5",
    "slot": "A",
    "weaponType": "WARHAMMER",
    "level": 5,
    "name": "Martillo de guerra estremecedor",
    "nameEn": "Quaking Warhammer",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer a5 - quaking.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARHAMMER_0",
    "slot": "B",
    "weaponType": "WARHAMMER",
    "level": 0,
    "name": "Mango",
    "nameEn": "Haft",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer b0 - starter haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARHAMMER_1",
    "slot": "B",
    "weaponType": "WARHAMMER",
    "level": 1,
    "name": "Mango fortificado",
    "nameEn": "Fortified Haft",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer b1 - fortified haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARHAMMER_2",
    "slot": "B",
    "weaponType": "WARHAMMER",
    "level": 2,
    "name": "Mango del hombre muerto",
    "nameEn": "Deadman's Haft",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer b2 - deadman's haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARHAMMER_3",
    "slot": "B",
    "weaponType": "WARHAMMER",
    "level": 3,
    "name": "Mango de escamas de dragón",
    "nameEn": "Dragonscale Haft",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer b3 - dragonscale haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARHAMMER_4",
    "slot": "B",
    "weaponType": "WARHAMMER",
    "level": 4,
    "name": "Mango de madera de corazón",
    "nameEn": "Heartwood Haft",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer b4 - heartwood haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_B_WARHAMMER_5",
    "slot": "B",
    "weaponType": "WARHAMMER",
    "level": 5,
    "name": "Mango de atalaya",
    "nameEn": "Watchtower Haft",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer b5 - watchtower haft.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARHAMMER_0",
    "slot": "C",
    "weaponType": "WARHAMMER",
    "level": 0,
    "name": "Puño",
    "nameEn": "Pommel",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer c0 - starter pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARHAMMER_1",
    "slot": "C",
    "weaponType": "WARHAMMER",
    "level": 1,
    "name": "Puño reblandecedor",
    "nameEn": "Tenderizer Pommel",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer c1 - tenderizer pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARHAMMER_2",
    "slot": "C",
    "weaponType": "WARHAMMER",
    "level": 2,
    "name": "Puño de espolón",
    "nameEn": "Talon Pommel",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer c2 - talon pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARHAMMER_3",
    "slot": "C",
    "weaponType": "WARHAMMER",
    "level": 3,
    "name": "Puño de Sahe",
    "nameEn": "Sahe Pommel",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer c3 - sahe pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARHAMMER_4",
    "slot": "C",
    "weaponType": "WARHAMMER",
    "level": 4,
    "name": "Puño de corona",
    "nameEn": "Crown Pommel",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer c4 - crown pommel.png",
    "buyPrice": null,
    "sellPrice": null
  },
  {
    "id": "WEAPON_PART_C_WARHAMMER_5",
    "slot": "C",
    "weaponType": "WARHAMMER",
    "level": 5,
    "name": "Puño de bastión",
    "nameEn": "Bastion Pommel",
    "weaponId": "WEAPON_WAR_HAMMER",
    "image": "/assets/weapon_parts/warhammer c5 - bastion pommel.png",
    "buyPrice": null,
    "sellPrice": null
  }
];

export const WEAPON_PARTS_BY_ID = Object.fromEntries(WEAPON_PARTS.map(p => [p.id, p]));

// Partes agrupadas por arma y slot
export const WEAPON_PARTS_BY_WEAPON = WEAPON_PARTS.reduce((acc, part) => {
  if (!acc[part.weaponId]) acc[part.weaponId] = {};
  if (!acc[part.weaponId][part.slot]) acc[part.weaponId][part.slot] = [];
  acc[part.weaponId][part.slot].push(part);
  return acc;
}, {});
